export const ADD_COMMENTS='ADD_COMMENTS'
export const DISHES_LOADING='DISHES_LOADING'
export const DISHES_FAILED='DISHES_FAILED'
export const ADD_DISHES='ADD_DISHES'

export const ADD_PROMOS='ADD_PROMOTIONS'
export const PROMOS_LOADING='PROMO_LOADING'
export const PROMOS_FAILED='PROMO_FAILED'

export const ADD_COMMENT='ADD_COMMENT'
export const COMMENTS_FAILED = 'COMMENTS_FAILED'