export const ADD_COMMENTS='ADD_COMMENTS'
export const DISHES_LOADING='DISHES_LOADING'
export const DISHES_FAILED='DISHES_FAILED'
export const ADD_DISHES='ADD_DISHES'
export const REFRESH_DISH='REFRESH_DISH'

export const ADD_PROMOS='ADD_PROMOTIONS'
export const PROMOS_LOADING='PROMO_LOADING'
export const PROMOS_FAILED='PROMO_FAILED'

export const ADD_LEADERS='ADD_LEADERS'
export const LEADER_LOADING='LEADER_LOADING'
export const LEADER_FAILED='LEADER_FAILED'

export const ADD_COMMENT='ADD_COMMENT'
export const COMMENTS_FAILED = 'COMMENTS_FAILED'
export const EDIT_COMMENT='EDIT_COMMENT'
export const DELETE_COMMENT='DELETE_COMMENT'

export const LOGIN='LOGIN'
export const LOGOUT='LOGOUT'
export const REGISTER='REGISTER'
export const AVAILABLEUSERNAME='AVAILABLEUSERNAME'


export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';